spring:
  application:
          name: api-gateway
server:
  port: 5556

# routes to serviceId
zuul:
    routes:
       api-a.path: /api-a/**
       api-a.serviceId: service-a
       api-b.path: /api-b/**
       api-b.serviceId: service-b


# routes to url
#       api-a-url.path: /ui/**
#       api-a-url.url: ui
#       api-b-url.path: /ui/**
#       api-b-url.url: ui
#routes:
#     api-a-url.path: /api-a-url/**
#     api-a-url.url: http://localhost:2222/

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:5555/eureka/