spring:
  application:
          name: api-gateway
server:
  port: 9001

# routes to serviceId
zuul:
    routes:
       api-open.path: /api-open/**
       api-open.serviceId: open-service
#       api-b.path: /api-b/**
#       api-b.serviceId: service-b


# routes to url
#zuul:
#    routes:
#       openservice-url.path: /**
#       openservice-url.url: ui
#routes:
#     api-a-url.path: /api-a-url/**
#     api-a-url.url: http://localhost:2222/

eureka:
  client:
    serviceUrl.defaultZone: http://localhost:9003/eureka/