spring:
  application:
          name: api-gateway
server:
  port: 9001

# routes to open-service
zuul:
    routes:
       api-open.path: /api-open/**
       api-open.serviceId: open-service


eureka:
  client:
    serviceUrl.defaultZone: http://localhost:9003/eureka/