#spring:
#   cloud:
#      config:
#         uri: http://127.0.0.1:${config.port:8888}
#         name: service-a
#         profile: ${config.profile:dev}

spring:
   application:
         name: service-a
server:
   port: 2222

eureka:
    client:
      serviceUrl.defaultZone: http://localhost:5555/eureka/